# Site settings
title: Paper Theme
description: > # this means to ignore newlines until "baseurl:"
  A gentle theme for Jekyll utilising material design.
# Your site's domain goes here (eg: //shanhh.com, https://shanhh.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://127.0.0.1:4000
baseurl: '/' # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: Dan Shan # your name
bio:    # your bio
email: i@shanhh.com
email_md5: ede7321f1c1a33e02e679abbddaf4b3d # md5 hash of your email
twitter_username:
github_username:

# Theming options
# These settings are mandatory.
materialtheme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
